info: "This is the local configuration, copy this file and then change details"

help: "Please enter a list of databses below. This is a list with the connection details"

databases:
  data:
    user: mashs
    password: mass
    database: fgxmap
    host: localhost
    socket: foo
