natural_earth_landmass:
    title: "NE Landmass"
    url: "http://map.fgx.ch:81/mapnik/fgxcache.py?"
    vars: 
        layers: natural_earth_landmass
        format: image/png
        isBaselayer: true 
    visibility: false
    
Airfield: 
    title: "Airfield"
    url: "http://map.fgx.ch:81/mapnik/fgxcache.py?"
    vars:
        layers: Airfield
        format: image/png
        transparent: true
    visibility: false

Runway: 
    title: "Runway"
    url: "http://map.fgx.ch:81/mapnik/fgxcache.py?"
    vars:
        layers: Runway
        format: image/png
        transparent: true
    visibility: false
    
VOR: 
    title: "VOR"
    url: "http://map.fgx.ch:81/mapnik/fgxcache.py?"
    vars:
        layers: VOR
        format: image/png
        transparent: true
    visibility: false

DME: 
    title: "DME"
    url: "http://map.fgx.ch:81/mapnik/fgxcache.py?"
    vars: 
        layers: DME 
        format: image/png
        transparent: true
    visibility: false

    
NDB: 
    title: "NDB"
    url: "http://map.fgx.ch:81/mapnik/fgxcache.py?"
    vars: 
        layers: NDB 
        format: image/png
        transparent: true
        
    visibility: false
    
ILS:
    title: "ILS"
    url: "http://map.fgx.ch:81/mapnik/fgxcache.py?"
    vars:
        layers: ILS 
        format: image/png
        transparent: true
    visibility: false
    
ILS_Info: 
    title: "ILS Info"
    url: "http://map.fgx.ch:81/mapnik/fgxcache.py?"
    vars:
        layers: ILS_Info 
        format: image/png
        transparent: true
    visibility: false

    
ILS_Marker:
    title: "ILS Marker"
    url: "http://map.fgx.ch:81/mapnik/fgxcache.py?"
    vars:
        layers:: ILS_Marker 
        format: image/png
        transparent: true
    visibility: false
    
FIX: 
    title: "FIX"
    url: "http://map.fgx.ch:81/mapnik/fgxcache.py?"
    vars:
        layers: FIX 
        format: image/png
        transparent: true
    visibility: false